name: SSH server with ngrok

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server wget
      - name: Configure SSH server
        run: |
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart
      - name: Download and install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
      - name: Authenticate with ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      - name: Create ngrok tunnel
        id: ngrok_tunnel
        run: |
          ./ngrok tcp 22 --region=us > /dev/null &
          echo "Waiting for ngrok tunnel to be established..."
          sleep 1m
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "::set-output name=ngrok_url::$NGROK_URL"
      - name: Output public IP address of ngrok tunnel
        run: echo "Public IP address: ${{ steps.ngrok_tunnel.outputs.ngrok_url }}"
      - name: Start SSH loop
        run: |
          echo "Starting SSH loop..."
          while true; do
            ssh -o StrictHostKeyChecking=no -R 80:localhost:22 ${{ steps.ngrok_tunnel.outputs.ngrok_url }}
            sleep 10
          done
